<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="testcases.TC002_LoginForNegative" tests="4" time="107.670" ignored="3" failures="0" timestamp="10 Mar 2018 11:17:49 GMT" skipped="0" hostname="dell-PC" errors="3">
  <testcase name="loginAndLogout" time="33.696" classname="testcases.TC002_LoginForNegative">
    <error type="java.lang.RuntimeException">
      <![CDATA[java.lang.RuntimeException
	at utils.Reporter.reportStep(Reporter.java:61)
	at utils.Reporter.reportStep(Reporter.java:71)
	at wdMethods.SeMethods.verifyPartialText(SeMethods.java:240)
	at pages.LoginPage.verifyErrorMsg(LoginPage.java:56)
	at testcases.TC002_LoginForNegative.loginAndLogout(TC002_LoginForNegative.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- loginAndLogout -->
  <testcase name="loginAndLogout" time="19.928" classname="testcases.TC002_LoginForNegative">
    <error type="java.lang.RuntimeException">
      <![CDATA[java.lang.RuntimeException
	at utils.Reporter.reportStep(Reporter.java:61)
	at utils.Reporter.reportStep(Reporter.java:71)
	at wdMethods.SeMethods.click(SeMethods.java:135)
	at pages.LoginPage.clickLogInForFailer(LoginPage.java:48)
	at testcases.TC002_LoginForNegative.loginAndLogout(TC002_LoginForNegative.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- loginAndLogout -->
  <testcase name="loginAndLogout" time="26.248" classname="testcases.TC002_LoginForNegative"/>
  <testcase name="loginAndLogout" time="27.798" classname="testcases.TC002_LoginForNegative">
    <error type="java.lang.RuntimeException">
      <![CDATA[java.lang.RuntimeException
	at utils.Reporter.reportStep(Reporter.java:61)
	at utils.Reporter.reportStep(Reporter.java:71)
	at wdMethods.SeMethods.click(SeMethods.java:135)
	at pages.LoginPage.clickLogInForFailer(LoginPage.java:48)
	at testcases.TC002_LoginForNegative.loginAndLogout(TC002_LoginForNegative.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- loginAndLogout -->
  <testcase name="afterTest" classname="wdMethods.ProjectMethods">
    <skipped/>
  </testcase> <!-- afterTest -->
  <testcase name="beforeSuite" classname="wdMethods.ProjectMethods">
    <skipped/>
  </testcase> <!-- beforeSuite -->
  <testcase name="afterSuite" classname="wdMethods.ProjectMethods">
    <skipped/>
  </testcase> <!-- afterSuite -->
</testsuite> <!-- testcases.TC002_LoginForNegative -->
